---
- name: Deploy Unmanic
  hosts: all
  become: true
  tasks:
    - name: Ensure required packages are installed
      package:
        name:
          - docker
        state: present

    - name: Ensure Docker is running
      service:
        name: docker
        state: started
        enabled: yes

    - name: Create unmanic/config directory on target host
      file:
        path: "{{ unmanic_config_path }}"
        state: directory
        mode: "0755"

    - name: Create unmanic/tmp directory on target host
      file:
        path: "{{ unmanic_tmp_path }}"
        state: directory
        mode: "0755"

    - name: Create NFS Docker volume
      community.docker.docker_volume:
        name: media 
        driver: local
        driver_options:
          type: nfs
          o: addr={{ nfs_server }},rw,nfsvers=3
          device: "{{ nfs_media_path }}"

    - name: Deploy Unmanic container
      community.docker.docker_container:
        name: unmanic
        image: josh5/unmanic:latest
        state: started
        recreate: yes
        pull: true
        restart_policy: unless-stopped
        runtime: nvidia
        env:
          PUID: "1000"
          PGID: "1000"
          TZ: "{{ timezone }}"
          VERSION: "docker"
          NVIDIA_VISIBLE_DEVICES: "all"
        volumes:
          - "{{ unmanic_config_path }}:/config"
          - "{{ unmanic_tmp_path }}:/tmp/unmanic"
          - "media:/library"
        ports:
          - 8888:8888
