---
- name: Deploy Tdarr Server and Node
  hosts: all
  become: true
  vars:
    server_directories:
      - "server"
      - "configs"
      - "logs"

  tasks:
    - name: Ensure required packages are installed
      package:
        name:
          - docker
        state: present

    - name: Ensure Docker is running
      service:
        name: docker
        state: started
        enabled: yes

    - name: Create required directories for server
      ansible.builtin.file:
        path: "{{ tdarr_file_path }}/{{ item }}"
        state: directory
        mode: '0755'
      loop: "{{ server_directories }}"

    - name: Create media NFS Docker volume
      community.docker.docker_volume:
        name: media
        driver: local
        driver_options:
          type: nfs
          o: addr={{ nfs_server }},rw,nfsvers=4,soft
          device: "{{ nfs_media_path }}"

    - name: Create transcode_cache NFS Docker volume
      community.docker.docker_volume:
        name: transcode_cache
        driver: local
        driver_options:
          type: nfs
          o: addr={{ nfs_server }},rw,nfsvers=4,soft
          device: "{{ tdarr_nfs_transcode_cache_path }}"

    - name: Create Docker network
      community.docker.docker_network:
        name: tdarr_network
        state: present

    - name: Deploy Tdarr Server container
      community.docker.docker_container:
        name: tdarr
        image: ghcr.io/haveagitgat/tdarr:latest
        state: started
        recreate: yes
        pull: true
        restart_policy: unless-stopped
        network_mode: tdarr_network
        ports:
          - "8265:8265"
          - "8266:8266"
        env:
          TZ: "{{ timezone }}"
          PUID: "{{ tdarr_puid }}"
          PGID: "{{ tdarr_pgid }}"
          UMASK_SET: "002"
          serverIP: "0.0.0.0"
          serverPort: "8266"
          webUIPort: "8265"
          internalNode: "true"
          inContainer: "true"
          nodeName: "tdarr-server"
          NVIDIA_VISIBLE_DEVICES: "all"
          NVIDIA_DRIVER_CAPABILITIES: "compute,utility,video"
        volumes:
          - "{{ tdarr_file_path }}/server:/app/server"
          - "{{ tdarr_file_path }}/configs:/app/configs"
          - "{{ tdarr_file_path }}/logs:/app/logs"
          - "media:/media"
          - "{{ tdarr_file_path }}/transcode_cache:/temp"
        device_requests:
          - driver: nvidia
            count: -1
            capabilities: [['gpu'], ['nvidia']]
        runtime: nvidia
        devices:
          - "/dev/nvidia0:/dev/nvidia0"
          - "/dev/nvidiactl:/dev/nvidiactl"
          - "/dev/nvidia-modeset:/dev/nvidia-modeset"
          - "/dev/nvidia-uvm:/dev/nvidia-uvm"
          - "/dev/nvidia-uvm-tools:/dev/nvidia-uvm-tools"
        capabilities:
          - SYS_ADMIN
