---
- name: Deploy Prometheus
  hosts: prometheus
  become: true
  tasks:
    - name: Ensure required packages are installed
      ansible.builtin.package:
        name:
          - docker
        state: present

    - name: Create Prometheus directory
      ansible.builtin.file:
        path: "{{ prometheus_config_path }}"
        state: directory
        mode: "0755"

    - name: Create prometheus.yml
      ansible.builtin.template:
        src: prometheus.yml.j2
        dest: "{{ prometheus_config_path }}/prometheus.yml"
        mode: "0755"

    - name: Create Prometheus rules.yml
      ansible.builtin.template:
        src: rules.yml.j2
        dest: "{{ prometheus_config_path }}/rules.yml"
        mode: "0755"

    - name: Deploy Prometheus container
      community.docker.docker_container:
        name: prometheus
        image: prom/prometheus:latest
        state: started
        recreate: true
        pull: true
        restart_policy: unless-stopped
        volumes:
          - "{{ prometheus_config_path }}:/etc/prometheus"
        command:
          - '--config.file=/etc/prometheus/prometheus.yml'
          - '--web.enable-lifecycle'
        ports:
          - 9090:9090
...
