---
- name: Deploy Ansible Semaphore
  hosts: semaphore
  strategy: linear
  become: true
  vars:
    semaphore_image: "semaphoreui/semaphore:{{ semaphore_version }}"
  tasks:

    - name: Clone private repository
      ansible.builtin.git:
        repo: "git@github.com:christopherime/ansible-vaults.git"
        dest: "ansible-vaults"
        version: main
        accept_hostkey: true
      delegate_to: localhost
      run_once: true
      become: false

    - name: Include variables from the vault
      ansible.builtin.include_vars: "ansible-vaults/semaphore"
      delegate_to: localhost
      run_once: true
      no_log: true

    - name: Ensure required packages are installed
      ansible.builtin.package:
        name:
          - docker
        state: present

    - name: Ensure Docker is running
      ansible.builtin.service:
        name: docker
        state: started
        enabled: "{{ docker_systemd_enable | default(omit) }}"

    - name: Pull Docker Images
      community.docker.docker_image:
        name: "{{ item }}"
        source: pull
      loop:
        - postgres:14
        - "{{ semaphore_image }}"

    - name: Ensure correct permissions for /var/lib/semaphore
      ansible.builtin.file:
        path: /var/lib/semaphore
        state: directory
        mode: '0777'

    - name: Ensure correct permissions for /var/lib/semaphore/playbooks
      ansible.builtin.file:
        path: /var/lib/semaphore/playbooks
        state: directory
        mode: '0777'

    - name: Ensure postgres volume is created
      community.docker.docker_volume:
        name: semaphore-postgres
        state: present

    - name: Create semaphore_network in docker
      community.docker.docker_network:
        name: semaphore_network
        state: present

    - name: Ensure postgres container is running
      community.docker.docker_container:
        name: postgres
        image: postgres:14
        state: started
        restart_policy: unless-stopped
        ports:
          - "5432:5432"
        volumes:
          - "semaphore-postgres:/var/lib/postgresql/data"
        env:
          POSTGRES_USER: "{{ postgres_user }}"
          POSTGRES_PASSWORD: "{{ postgres_password }}"
          POSTGRES_DB: "semaphore"
        networks:
          - name: semaphore_network

    - name: Ensure semaphore container is running
      community.docker.docker_container:
        name: semaphore
        image: "{{ semaphore_image }}"
        state: started
        restart_policy: unless-stopped
        ports:
          - "3021:3000"
        volumes:
          - "/var/lib/semaphore:/tmp/semaphore/"
        env:
          SEMAPHORE_DB_USER: "{{ postgres_user }}"
          SEMAPHORE_DB_PASS: "{{ postgres_password }}"
          SEMAPHORE_DB_HOST: "postgres"
          SEMAPHORE_DB_PORT: "5432"
          SEMAPHORE_DB_DIALECT: "postgres"
          SEMAPHORE_DB: "semaphore"
          SEMAPHORE_PLAYBOOK_PATH: "/var/lib/semaphore/playbooks"
          SEMAPHORE_ADMIN_PASSWORD: "{{ semaphore_admin_password }}"
          SEMAPHORE_ADMIN_NAME: "{{ semaphore_admin_name }}"
          SEMAPHORE_ADMIN_EMAIL: "{{ semaphore_admin_email }}"
          SEMAPHORE_ADMIN: "admin"
          SEMAPHORE_ACCESS_KEY_ENCRYPTION: "{{ semaphore_access_key_encryption }}"
          SEMAPHORE_LDAP_ACTIVATED: "no"
        networks:
          - name: semaphore_network
  handlers:
    - name: Restart docker
      ansible.builtin.service:
        name: docker
        state: restarted
      listen: "restart docker"
...
