---
- name: Deploy Plex Media Server
  hosts: all
  become: true
  tasks:
    - name: Ensure required packages are installed
      package:
        name:
          - docker
        state: present

    - name: Ensure Docker is running
      service:
        name: docker
        state: started
        enabled: yes

    - name: Create directory Plex config
      ansible.builtin.file:
        path: /media/sdb/plex_config
        state: directory
        mode: '0755'

    - name: Create media NFS Docker volume
      community.docker.docker_volume:
        name: media
          #recreate: always
        driver: local
        driver_options:
          type: nfs
          o: addr={{ nfs_server }},rw,nfsvers=4,soft
          device: "{{ nfs_media_path }}"

    - name: Deploy Plex container
      community.docker.docker_container:
        name: plex
        image: lscr.io/linuxserver/plex:latest
        state: started
        recreate: yes
        pull: true
        restart_policy: unless-stopped
        network_mode: host
        runtime: nvidia
        env:
          PUID: "{{ nfs_plex_puid }}"
          PGID: "{{ nfs_plex_pgid }}"
          TZ: "{{ timezone }}"
          VERSION: "docker"
          NVIDIA_VISIBLE_DEVICES: "all"
          PLEX_CLAIM: "claim-pyWbYxxBeLGfdxU9zz9J"
        volumes:
          - "/media/sdb/plex_config:/config"
          - "media:/media"
