---
- name: Deploy Plex Media Server
  hosts: plex
  become: true
  tasks:
    - name: Ensure required packages are installed
      ansible.builtin.package:
        name:
          - docker
        state: present

    - name: Ensure Docker is running
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true

    - name: Create directory Plex config
      ansible.builtin.file:
        path: "{{ plex_config_file_path }}"
        state: directory
        mode: '0755'

    - name: Create media NFS Docker volume
      community.docker.docker_volume:
        name: media
        driver: local
        driver_options:
          type: nfs
          o: addr={{ nfs_server }},rw,nfsvers=4,soft
          device: "{{ nfs_media_path }}"

    - name: Deploy Plex container
      community.docker.docker_container:
        name: plex
        image: lscr.io/linuxserver/plex:latest
        state: started
        recreate: false
        pull: true
        restart_policy: unless-stopped
        network_mode: host
        runtime: nvidia
        env:
          VERSION: "docker"
          TZ: "{{ timezone }}"
          PUID: "{{ nfs_plex_puid }}"
          PGID: "{{ nfs_plex_pgid }}"
          PLEX_CLAIM: "{{ plex_claim }}"
          NVIDIA_VISIBLE_DEVICES: "all"
        volumes:
          - "{{ plex_config_file_path }}:/config"
          - "media:/media"
...
