---
- name: Update package
  hosts: all
  become: yes
  tasks:
    - name: Update package
      apt:
        update_cache: yes
        upgrade: yes
      when: ansible_os_family == "Debian"
    - name: Update package
      yum:
        name: '*'
        state: latest
      when: ansible_os_family == "RedHat"
