---
- name: Update package
  hosts: all
  become: true
  tasks:
    - name: Update package apt
      ansible.builtin.apt:
        update_cache: true
        upgrade: true
      when: ansible_os_family == "Debian"
...
